version = "Two"
edition = "2018"
unstable_features = true
force_explicit_abi = true
max_width = 120
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
use_try_shorthand = true

wrap_comments = true

trailing_comma = "Always"
trailing_semicolon = true

space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
where_single_line = true

imports_indent = "Visual"
imports_layout = "Mixed"
merge_imports  = true
merge_derives  = true

brace_style = "PreferSameLine"
empty_item_single_line = true
normalize_comments = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true

type_punctuation_density = "Wide"

indent_style = "Visual"
fn_args_layout = "Tall"
fn_single_line = true
struct_lit_single_line = false
use_field_init_shorthand = true

format_macro_matchers = true
format_macro_bodies = true

match_arm_blocks = true
match_block_trailing_comma = true

use_small_heuristics = "Max"
condense_wildcard_suffixes = true
struct_field_align_threshold = 99
